# Generated by Django 6.0 on 2026-03-13 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GridNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Stable', 'Stable'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Offline', 'Offline')], default='Stable', max_length=20)),
                ('demand', models.FloatField(default=0.0, help_text='Current demand/load')),
                ('input', models.FloatField(default=0.0, help_text='Current input flow (kV or kW)')),
                ('output', models.FloatField(default=0.0, help_text='Current output flow (kV or kW)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='grid.category')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionSubstation',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='DistributionTransformer',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='GridSubstation',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='GridEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TransmissionLine', 'Transmission Line'), ('SubTransmissionLine', 'Sub-Transmission Line'), ('Feeder11kV', '11 kV Feeder'), ('SecondaryDistributionLine', 'Secondary Distribution Line'), ('ServiceLine', 'Service Line')], max_length=50)),
                ('capacity', models.FloatField(default=100.0, help_text='Max flow capacity (kW)')),
                ('source', models.ForeignKey(help_text='Connection Input (ci): upstream node', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='grid.gridnode')),
                ('target', models.ForeignKey(help_text='Connection Output (co): downstream node', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='grid.gridnode')),
            ],
        ),
    ]
