# Generated by Django 6.0 on 2026-03-13 16:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GridNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Stable', 'Stable'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Offline', 'Offline')], default='Stable', max_length=20)),
                ('input', models.FloatField(default=0.0, help_text='Current input flow (kV or kW)')),
                ('output', models.FloatField(default=0.0, help_text='Current output flow (kV or kW)')),
                ('power_active', models.BooleanField(default=True, help_text='True only if this node is NOT Offline AND its parent is also power_active. Automatically propagated through the hierarchy.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='grid.category')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionSubstation',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='GridSubstation',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='DistributionTransformer',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
                ('distribution_substation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_transformers', to='grid.distributionsubstation')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.AddField(
            model_name='distributionsubstation',
            name='grid_substation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_substations', to='grid.gridsubstation'),
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
                ('distribution_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='grid.distributiontransformer')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
                ('distribution_transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industries', to='grid.distributiontransformer')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.AddField(
            model_name='gridsubstation',
            name='power_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_substations', to='grid.powerplant'),
        ),
        migrations.CreateModel(
            name='GridEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TransmissionLine', 'Transmission Line (400–765 kV)'), ('SubTransmissionLine', 'Sub-Transmission Line (132/66/33 kV)'), ('Feeder11kV', '11 kV Feeder'), ('SecondaryDistributionLine', 'Secondary Distribution Line (415/230 V)'), ('ServiceLine', 'Service Line')], max_length=50)),
                ('capacity', models.FloatField(default=0.0, help_text='Rated capacity in kW')),
                ('active', models.BooleanField(default=True, help_text='Mirrors target node power_active')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='grid.gridnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='grid.gridnode')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
