# Generated by Django 6.0 on 2026-03-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder11kV',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='SecondaryDistributionLine',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='StepUpTransformer',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
        migrations.CreateModel(
            name='TransmissionLine',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
    ]
