# Generated by Django 6.0 on 2026-03-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_feeder11kv_secondarydistributionline_serviceline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTransmissionLine',
            fields=[
                ('gridnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grid.gridnode')),
            ],
            bases=('grid.gridnode',),
        ),
    ]
