# Generated by Django 6.0 on 2026-03-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_subtransmissionline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepUpTransformer',
        ),
    ]
