# Generated by Django 6.0 on 2026-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_delete_stepuptransformer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributiontransformer',
            name='gridnode_ptr',
        ),
        migrations.DeleteModel(
            name='DistributionSubstation',
        ),
        migrations.DeleteModel(
            name='DistributionTransformer',
        ),
    ]
